// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feedback.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO feedback (user_id, project_id, author_name, author_email, message, rating, source)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, project_id, author_name, author_email, message, rating, source, received_at
`

type CreateFeedbackParams struct {
	UserID      pgtype.UUID
	ProjectID   pgtype.UUID
	AuthorName  string
	AuthorEmail pgtype.Text
	Message     string
	Rating      pgtype.Int4
	Source      string
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (Feedback, error) {
	row := q.db.QueryRow(ctx, createFeedback,
		arg.UserID,
		arg.ProjectID,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.Message,
		arg.Rating,
		arg.Source,
	)
	var i Feedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.Message,
		&i.Rating,
		&i.Source,
		&i.ReceivedAt,
	)
	return i, err
}

const deleteFeedback = `-- name: DeleteFeedback :execrows
DELETE FROM feedback
WHERE id = $1 AND project_id = $2 AND user_id = $3
`

type DeleteFeedbackParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) DeleteFeedback(ctx context.Context, arg DeleteFeedbackParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFeedback, arg.ID, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listProjectFeedback = `-- name: ListProjectFeedback :many
SELECT id, user_id, project_id, author_name, author_email, message, rating, source, received_at FROM feedback
WHERE project_id = $1 AND user_id = $2
ORDER BY received_at DESC
`

type ListProjectFeedbackParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) ListProjectFeedback(ctx context.Context, arg ListProjectFeedbackParams) ([]Feedback, error) {
	rows, err := q.db.Query(ctx, listProjectFeedback, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feedback
	for rows.Next() {
		var i Feedback
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.Message,
			&i.Rating,
			&i.Source,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
