// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLink = `-- name: CreateLink :one
INSERT INTO links (user_id, project_id, kind, url, label, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, project_id, kind, url, label, notes, created_at, updated_at
`

type CreateLinkParams struct {
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	Kind      string
	Url       string
	Label     string
	Notes     string
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.UserID,
		arg.ProjectID,
		arg.Kind,
		arg.Url,
		arg.Label,
		arg.Notes,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Kind,
		&i.Url,
		&i.Label,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :execrows
DELETE FROM links
WHERE id = $1 AND project_id = $2 AND user_id = $3
`

type DeleteLinkParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) DeleteLink(ctx context.Context, arg DeleteLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLink, arg.ID, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listProjectLinks = `-- name: ListProjectLinks :many
SELECT id, user_id, project_id, kind, url, label, notes, created_at, updated_at FROM links
WHERE project_id = $1 AND user_id = $2
ORDER BY created_at ASC
`

type ListProjectLinksParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) ListProjectLinks(ctx context.Context, arg ListProjectLinksParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listProjectLinks, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Link
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Kind,
			&i.Url,
			&i.Label,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET kind = $4,
    url = $5,
    label = $6,
    notes = $7,
    updated_at = now()
WHERE id = $1 AND project_id = $2 AND user_id = $3
RETURNING id, user_id, project_id, kind, url, label, notes, created_at, updated_at
`

type UpdateLinkParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
	Kind      string
	Url       string
	Label     string
	Notes     string
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Kind,
		arg.Url,
		arg.Label,
		arg.Notes,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Kind,
		&i.Url,
		&i.Label,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
