// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Feedback struct {
	ID pgtype.UUID
	// auth.users.id
	UserID      pgtype.UUID
	ProjectID   pgtype.UUID
	AuthorName  string
	AuthorEmail pgtype.Text
	Message     string
	Rating      pgtype.Int4
	Source      string
	ReceivedAt  pgtype.Timestamptz
}

type Link struct {
	ID pgtype.UUID
	// auth.users.id
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	Kind      string
	Url       string
	Label     string
	Notes     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Note struct {
	ID pgtype.UUID
	// auth.users.id
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	Body      string
	CreatedAt pgtype.Timestamptz
}

type Project struct {
	ID pgtype.UUID
	// auth.users.id
	UserID            pgtype.UUID
	Name              string
	Slug              string
	Status            string
	Stack             string
	Summary           string
	FeedbackIngestKey string
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	// Origin of the embedding site (scheme + host), e.g. https://myapp.com. Empty allows any origin.
	FeedbackOrigin string
}

type RoadmapItem struct {
	ID pgtype.UUID
	// auth.users.id
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	Title     string
	Status    string
	SortOrder int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
