// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (user_id, project_id, body)
VALUES ($1, $2, $3)
RETURNING id, user_id, project_id, body, created_at
`

type CreateNoteParams struct {
	UserID    pgtype.UUID
	ProjectID pgtype.UUID
	Body      string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, arg.UserID, arg.ProjectID, arg.Body)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM notes
WHERE id = $1 AND project_id = $2 AND user_id = $3
`

type DeleteNoteParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listProjectNotes = `-- name: ListProjectNotes :many
SELECT id, user_id, project_id, body, created_at FROM notes
WHERE project_id = $1 AND user_id = $2
ORDER BY created_at DESC
`

type ListProjectNotesParams struct {
	ProjectID pgtype.UUID
	UserID    pgtype.UUID
}

func (q *Queries) ListProjectNotes(ctx context.Context, arg ListProjectNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listProjectNotes, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
