// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, name, slug, status, stack, summary)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, slug, status, stack, summary, feedback_ingest_key, created_at, updated_at
`

type CreateProjectParams struct {
	UserID  pgtype.UUID
	Name    string
	Slug    string
	Status  string
	Stack   string
	Summary string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.Status,
		arg.Stack,
		arg.Summary,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Stack,
		&i.Summary,
		&i.FeedbackIngestKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects
WHERE id = $1 AND user_id = $2
`

type DeleteProjectParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, name, slug, status, stack, summary, feedback_ingest_key, created_at, updated_at FROM projects
WHERE id = $1 AND user_id = $2
`

type GetProjectParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, arg.ID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Stack,
		&i.Summary,
		&i.FeedbackIngestKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, user_id, name, slug, status, stack, summary, feedback_ingest_key, created_at, updated_at FROM projects
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context, userID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.Stack,
			&i.Summary,
			&i.FeedbackIngestKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ping = `-- name: Ping :one
SELECT 1
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $3,
    slug = $4,
    status = $5,
    stack = $6,
    summary = $7,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, slug, status, stack, summary, feedback_ingest_key, created_at, updated_at
`

type UpdateProjectParams struct {
	ID      pgtype.UUID
	UserID  pgtype.UUID
	Name    string
	Slug    string
	Status  string
	Stack   string
	Summary string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.Status,
		arg.Stack,
		arg.Summary,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.Stack,
		&i.Summary,
		&i.FeedbackIngestKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
